## numpy
* 가장 기초적인 개체  (mutable)
    - 같은 데이터 타입을 가져야 함함
    - 양의 정수로 구성된 튜플로 인덱싱함
    - 차원은 axis(축)이라고 함 -> axis(0) 첫번째 축(2차원부터 세로), axis(1) 두번째 축 (2차원부터는 가로) 가로세로 크게 상관 없음

In [1]:
import numpy as np

##### array를 만드는 다양한 방법

In [8]:
a = np.array([[1,2,3],[4,5,6]]) #리스트 형태로 만들어 전달함
print(a) #shape = (2,3) -> 몇층 몇호
print(type(a)) # 타입 확인
print(a.ndim)  # 몇차원인가?
print(a.shape) # shape
print(a.size)  # 원소의 갯수
print(a.dtype) # 데이터 타입
print(a.itemsize) # 각 원소가 차지하는 데이터
print(a.data)  # 이 데이터의 고유 주소

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
6
int64
8


In [10]:
b = np.ndarray((2,2)) # 인자로 튜플로 이루어진 shape을 넘겨줌
print(b) # 내용물을 지정하지 않았기 때문에 임의으 값으로 생성함

[[ 1.68727212e-316  0.00000000e+000]
 [-1.49101788e-055  6.90935817e-310]]


In [11]:
c = np.array([[1,2],[3,4]], dtype = complex) # 데이터 타입 변경, complex - 복소수
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [12]:
np.zeros((3,4)) # shape을 넘겨주면 0으로 채워진 배열이 만들어짐

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,3,4), dtype = np.int16) # 1로 채워진 배열 생성

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [14]:
np.empty((2,3)) # 임의의 값으로 채운 shape의 배열

array([[1.68532432e-316, 0.00000000e+000, 6.90935792e-310],
       [6.90935792e-310, 6.90935792e-310, 2.25267892e+156]])

In [16]:
np.arange(10,30,5) # 시작값, 종료값(포함안됨), 간격 / 만약 간격이 소수일때는 규칙이 다름

array([10, 15, 20, 25])

In [17]:
np.linspace(0,2,9) # 시작값, 종료값(포함됨), 사이에 몇개? - 범위 내의 균등한 간격으로 생성됨

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
#list와 비슷한 출력 형태

a = np.arange(12).reshape(4,3)
b = np.arange(24).reshape(2,3,4)

print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [32]:
import sys

print(np.arange(1000)) # 너무 길면 중간 생략함
np.set_printoptions(threshold=sys.maxsize) # 프린트의 옵션을 바꿔줌
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

##### 인덱싱

In [24]:
# 인덱싱

x = np.arange(10)
x[2]

2

In [25]:
x[-2] # 뒤에서 두번째

8

In [26]:
x.shape = (2,5) #shape 변경
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
# 똑같은 표현임
print(x[0,2])
print(x[0][2])

2
2


In [35]:
#list, array를 활용한 인덱싱

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(a)
print()

print(a[[0,1,2,0], [0,2,0,1]]) # 0,0 1,2 2,0, 0,1 
print()

b = np.array([0,2,0,1])
print(a[b,b])
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 6 7 2]

[1 9 1 5]



In [41]:
# :을 사용한 인덱싱 [시작:끝:간격]

x = np.arange(10)
print(x[2:])    # 2번부터 끝까지
print(x[:5])    # 처음부터 5번까지
print(x[2:5])   # 2번부터 5번까지
print(x[:-7])   # 거꾸로 7번째까지 => x[len(x)-7:]
print(x[1:7:2]) # 1번부터 7번까지 두칸씩 건너뛰고(마지막 포함안됨)
print(x[::])    # 처음부터 끝까지

print()
y = np.arange(35).reshape(5,7)
print(y)
print(y[1:5:2, ::3]) # 행(1행부터 5행까지 2간격), 열(3간격으로 호출)

[2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[2 3 4]
[0 1 2]
[1 3 5]
[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 7 10 13]
 [21 24 27]]


In [45]:
# bool indexing

a = np.array(range(6)).reshape(2,3)
bool_idx = a > 2 # a의 대소비교를 한 리스트를 넣어줌
print(bool_idx)
print(a[bool_idx])
print(a[a>2])

[[False False False]
 [ True  True  True]]
[3 4 5]
[3 4 5]


In [48]:
# slicing - shallow copy가 이루어짐 !!!! 

a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(a)
print()

b = a[:2] #처음부터 2행까지
print(b)
print()

c = a[:, 1:3] #행 전체, 1열부터 3열까지
print(c)
print()

d = a[:, -1] # 행 전체, 마지막 열만
print(d)
print()

b[0,0] = -1 # b의 [0,0]의 값을 -1로 바꿈
print(a) # shallow copy라서 a의 값도 바뀌는 것
print()

e = np.copy(a[:2]) # deep copy
print(e)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]

[[ 2  3]
 [ 6  7]
 [10 11]]

[ 4  8 12]

[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[-1  2  3  4]
 [ 5  6  7  8]]


##### Shape Manipulation

In [50]:
a = np.random.random((3,4)) #랜덤한 값으로 생성 0~1 사이 값
a = np.floor(10*np.random.random((3,4))) #10을 곱한 후, 소수점을 날려버림(floor)
print(a)

[[2. 1. 9. 9.]
 [0. 0. 6. 7.]
 [4. 2. 8. 6.]]


In [51]:
y = np.random.random((3,4))
print(np.floor(y))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [52]:
a.ravel() # a의 차원이 1차원이 되면 어떨지 보여주는거

array([2., 1., 9., 9., 0., 0., 6., 7., 4., 2., 8., 6.])

In [53]:
print(a) # a를 수정하지 않음

[[2. 1. 9. 9.]
 [0. 0. 6. 7.]
 [4. 2. 8. 6.]]


In [54]:
a.reshape(6,2) # a의 차원을 바꾼 출력만 내놓음, 수정하진 않음, -1로 지정된 경우는 자동으로 계산됨

array([[2., 1.],
       [9., 9.],
       [0., 0.],
       [6., 7.],
       [4., 2.],
       [8., 6.]])

In [55]:
a.resize((6,2)) # 튜플로 사이즈를 감싸서 줘야함, 어레이 자체를 변경
print(a)

[[2. 1.]
 [9. 9.]
 [0. 0.]
 [6. 7.]
 [4. 2.]
 [8. 6.]]


##### 실습

In [65]:
# 실습 1
a = np.ones((5,5))
a[1:4,1:4] = 0
print(a)
print()

a = np.zeros((5,5))
a[1:4,1:4] = 1
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [82]:
# TA 코드

a = np.ones((5,5))
print(a)
print()

a[1:-1,1:-1] = 0 # 0번과 4번줄은 신경 쓸 필요 없음 1:-1 로 적어도 똑같음, a의 사이즈가 달라져도 똑같은 결과를 낳음
print(a)
print()

a = np.zeros((3,3)) # 속 만들고
print(a)
print()

b = np.pad(a, pad_width = 1, mode = 'constant', constant_values = 1) #겉에 패딩을 씌우는 역할, mode = 어떤 데이터 타입을 넣을건지
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [79]:
# 실습 2
b = np.zeros((8,8))
b[1::2,::2] = 1
b[::2,1::2] = 1
b

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [89]:
# TA 코드
a = np.zeros((8,8))
print(a)
print()

# 0 1 0 1 0 1...
a[::2,1::2] = 1 # 행: 0,2,4,6 / 열: 1,3,5,7
print(a)
print()

# 1 0 1 0 1 0...
a[1::2,::2] = 1 # 행: 1,3,5,7 / 열: 0,2,4,6
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [90]:
# 실습 3
a = np.array([180,72,172,66,162,60,167,53,176,80,155,60,177,77,130,40])
a.reshape(2,4,2)
a.resize((2,4,2))
print(a)

[[[180  72]
  [172  66]
  [162  60]
  [167  53]]

 [[176  80]
  [155  60]
  [177  77]
  [130  40]]]


In [92]:
# TA 코드
a = np.array([180,72,172,66,162,60,167,53,176,80,155,60,177,77,130,40])
a.resize((2,4,2)) # 반, 학생수, 학생의 정보
print(a)

[[[180  72]
  [172  66]
  [162  60]
  [167  53]]

 [[176  80]
  [155  60]
  [177  77]
  [130  40]]]


In [94]:
# + 인덱싱으로 접근하기
# B반 세번째 학생의 키는?
print(a[1][2][0])

177


##### Basic Operations

In [95]:
# elemetwise : 같은 사이즈의 배열일 때, 같은 위치에 있는 원소끼리 연산이 되는 현상

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y) #np.add(x,y)
print()

print(x - y) #np.sub(x,y)
print()

print(x * y) #np.multiply(x,y)
print()

print(x / y) #np.divide(x,y)

#이외에도 대소비교 가능( <, >, ==, !=, >=, <=)

[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]

[[ 5 12]
 [21 32]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [97]:
# 행렬곱, 닷프로덕트

print(x * y)
print()

print(x @ y)
print()

print(x.dot(y))

# 서로 다른 사이즈의 배열이어도, 한항의 값을 반대쪽의 크기에 맞게 확장하는 기능도 있음. 
# numpy.linalg - 선형대수학 연산 라이브러리


[[ 5 12]
 [21 32]]

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]
